"use strict";
// Local Node host. Vercel production uses api/chat.js; both keep Groq credentials server-side.
const http = require("http"), fs = require("fs"), path = require("path");
const envFile = path.join(__dirname, ".env");
if (fs.existsSync(envFile)) for (const line of fs.readFileSync(envFile, "utf8").split(/\r?\n/)) { const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/); if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, ""); }
const port = Number(process.env.PORT || 3000), root = path.join(__dirname, "public");
const MODEL = "openai/gpt-oss-120b", MAX_BODY = 60_000, MAX_MESSAGES = 18, MAX_CONTENT = 14_000;
const NEO_SYSTEM = "You are Neo, a warm, calm, capable personal AI assistant. Act first, make reasonable assumptions, and help before asking at most one necessary follow-up. Be direct, natural, concise, and never corporate or questionnaire-like. NEO supports text, supported-browser voice input, optional spoken responses, short-term context, and TXT/CSV/JSON/Markdown/HTML/JS/CSS/XML context. It has no live web access, external actions, PDF/Office parsing, or image parsing.";
function send(res,status,body,type="application/json"){res.writeHead(status,{"Content-Type":type,"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});res.end(type==="application/json"?JSON.stringify(body):body)}
function messagesFrom(value){if(!Array.isArray(value)||value.length<1||value.length>MAX_MESSAGES)return null;const messages=[];for(const item of value){if(!item||!["system","user","assistant"].includes(item.role)||typeof item.content!=="string"||!item.content.trim()||item.content.length>MAX_CONTENT)return null;if(item.role!=="system")messages.push({role:item.role,content:item.content})}return messages.length?[{role:"system",content:NEO_SYSTEM},...messages]:null}
async function chat(req,res){if(!process.env.GROQ_API_KEY)return send(res,503,{error:{message:"Server AI configuration is unavailable."}});let raw="",tooLarge=false;req.on("data",chunk=>{if(!tooLarge){raw+=chunk;if(raw.length>MAX_BODY)tooLarge=true}});req.on("end",async()=>{if(tooLarge)return send(res,413,{error:{message:"Request is too large."}});let payload;try{payload=JSON.parse(raw)}catch{return send(res,400,{error:{message:"Invalid JSON request."}})}const messages=messagesFrom(payload.messages);if(!messages)return send(res,400,{error:{message:"Invalid or oversized conversation."}});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const upstream=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+process.env.GROQ_API_KEY},body:JSON.stringify({model:MODEL,messages,temperature:.7,max_tokens:500}),signal:controller.signal});const data=await upstream.json().catch(()=>null);const content=data?.choices?.[0]?.message?.content;if(!upstream.ok||typeof content!=="string"||!content.trim())return send(res,upstream.status>=400?upstream.status:502,{error:{message:data?.error?.message||"AI service returned an invalid response."}});send(res,200,{choices:[{message:{role:"assistant",content}}]})}catch(error){send(res,error.name==="AbortError"?504:502,{error:{message:error.name==="AbortError"?"AI request timed out.":"Unable to reach the AI service."}})}finally{clearTimeout(timer)}})}
http.createServer((req,res)=>{if(req.method==="POST"&&req.url==="/api/chat")return chat(req,res);if(req.method!=="GET")return send(res,405,{error:{message:"Method not allowed."}});const requested=req.url==="/"?"/index.html":decodeURIComponent(req.url.split("?")[0]);const file=path.resolve(root,"."+requested);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return send(res,404,"Not found","text/plain");send(res,200,fs.readFileSync(file),path.extname(file)===".html"?"text/html; charset=utf-8":"application/octet-stream")}).listen(port,()=>console.log(`NEO local server listening on ${port}`));

