"use strict";
const http=require("http"),fs=require("fs"),path=require("path");const envFile=path.join(__dirname,".env");if(fs.existsSync(envFile))for(const line of fs.readFileSync(envFile,"utf8").split(/\r?\n/)){const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,"")}
const port=Number(process.env.PORT||3000),root=path.join(__dirname,"public"),MODEL="openai/gpt-oss-120b",MAX_MESSAGES=18,MAX_CONTENT=14000;
const NEO_SYSTEM="You are Neo, a warm, calm, capable personal AI assistant. Act first, help before asking at most one necessary follow-up, and be direct, natural, and concise. Do not be corporate or questionnaire-like.";
function reply(res,status,body,type="application/json; charset=utf-8"){res.writeHead(status,{"Content-Type":type,"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"});res.end(type.includes("application/json")?JSON.stringify(body):body)}
function messagesFrom(value){if(!Array.isArray(value)||value.length<1||value.length>MAX_MESSAGES)return null;const out=[];for(const item of value){if(!item||!["system","user","assistant"].includes(item.role)||typeof item.content!=="string"||!item.content.trim()||item.content.length>MAX_CONTENT)return null;if(item.role!=="system")out.push({role:item.role,content:item.content})}return out.length?[{role:"system",content:NEO_SYSTEM},...out]:null}
async function chat(req,res){let raw="";req.on("data",c=>raw+=c);req.on("end",async()=>{if(!process.env.GROQ_API_KEY)return reply(res,503,{ok:false,error:"AI service is not configured."});let payload;try{payload=JSON.parse(raw)}catch{return reply(res,400,{ok:false,error:"Invalid JSON request."})}const messages=messagesFrom(payload.messages);if(!messages)return reply(res,400,{ok:false,error:"Invalid or oversized conversation."});const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const upstream=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+process.env.GROQ_API_KEY},body:JSON.stringify({model:MODEL,messages,temperature:.7,max_tokens:500}),signal:controller.signal});const data=await upstream.json().catch(()=>null);const text=data?.choices?.[0]?.message?.content;if(!upstream.ok||typeof text!=="string"||!text.trim())return reply(res,upstream.status===429?429:502,{ok:false,error:upstream.status===429?"Rate limit reached. Try again shortly.":"AI service returned an invalid response."});reply(res,200,{ok:true,text:text.trim()})}catch(error){reply(res,error.name==="AbortError"?504:502,{ok:false,error:error.name==="AbortError"?"AI request timed out.":"Unable to reach the AI service."})}finally{clearTimeout(timer)}})}
http.createServer((req,res)=>{if(req.url==="/api/chat"){if(req.method!=="POST"){res.setHeader("Allow","POST");return reply(res,405,{ok:false,error:"Method not allowed."})}return chat(req,res)}if(req.method!=="GET")return reply(res,405,{ok:false,error:"Method not allowed."});const requested=req.url==="/"?"/index.html":decodeURIComponent(req.url.split("?")[0]),file=path.resolve(root,"."+requested);if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return reply(res,404,"Not found","text/plain; charset=utf-8");reply(res,200,fs.readFileSync(file),path.extname(file)===".html"?"text/html; charset=utf-8":"application/octet-stream")}).listen(port,()=>console.log(`NEO local server listening on ${port}`));

